_BASE_: "voc_R_50_C4_24k.yaml"
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  WEIGHTS: "pretrained weight path"
  RESNETS:
    STRIDE_IN_1X1: False
INPUT:
  FORMAT: "RGB"
OUTPUT_DIR: "./output"
